# Generated by Django 2.1.4 on 2019-01-26 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0006_periodictask_priority'),
        ('django_celery_results', '0003_auto_20181106_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amplifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('response_size', models.IntegerField()),
                ('amplification_factor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScanTimeSeriesResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('scan_name', models.CharField(max_length=255)),
                ('active_amplifiers_count', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('periodic_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series_results', to='django_celery_beat.PeriodicTask')),
                ('scan_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_series_result', to='django_celery_results.TaskResult')),
            ],
        ),
        migrations.AddField(
            model_name='amplifier',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amplifiers', to='core.ScanTimeSeriesResult'),
        ),
    ]
