# Generated by Django 2.1.4 on 2019-01-10 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amplifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('response_size', models.IntegerField()),
                ('amplification_factor', models.IntegerField()),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amplifiers', to='core.ScanTimeSeriesResult')),
            ],
        ),
    ]
