# Generated by Django 2.1.4 on 2019-02-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amplifier',
            old_name='response_size',
            new_name='total_response_size',
        ),
    ]
