# Generated by Django 2.1.4 on 2019-01-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_amplifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantimeseriesresult',
            name='status',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
