# Generated by Django 2.1.4 on 2019-02-01 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190201_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_hex_data', models.TextField()),
                ('response_size', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='amplifier',
            name='unsolicited_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='amplifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.Amplifier'),
        ),
    ]
