# Generated by Django 2.1.4 on 2019-02-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190201_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='amplifier',
            name='destination_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='response_dport',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='response_ipid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='response_sport',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='response_ttl',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
