# Generated by Django 2.1.4 on 2019-02-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190206_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='amplifier',
            name='private_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='amplifier',
            name='amplification_factor',
            field=models.FloatField(),
        ),
    ]
