# Generated by Django 2.1.4 on 2019-02-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190220_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantimeseriesresult',
            name='private_amplifiers_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scantimeseriesresult',
            name='public_amplifiers_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
