{
 "title": "Amplifier",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "amp_id", "query": "select id from core_amplifier;" },
   {
    "name": "amp_name",
    "query": "select address from core_amplifier where id=${amp_id}"
   },
   { "name": "scan_name" }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT address as \"Amplifier IP Address\", destination_address as \"Destination Address\", total_response_size as \"Total Response Size\", amplification_factor as \"Bandwidth Amplification Factor\", if(unsolicited_response, \"Yes\", \"No\") as \"Unsolicited Response\", if(private_address, \"Private\", \"Public\") as \"Amplifier Address Type\" from core_amplifier where id = \"$amp_id\""
    }
   ]
  },
  {
   "title": "Responses",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "select response_sport as \"Src Port\", response_dport as \"Dst Port\", response_ipid as \"IPID\", response_ttl as \"TTL\", response_size as \"Size\", response_hex_data as \"Hex Data\" from core_response where amplifier_id=\"$amp_id\""
    }
   ]
  },
  {
   "title": "Change In BAF",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select  b.created AS \"time\", address as \"metric\", a.amplification_factor from core_amplifier a join core_scantimeseriesresult b on a.scan_id=b.id where a.address=\"$amp_name\";"
    }
   ]
  }
 ]
}