{
 "title": "Home",
 "time": { "from": "2019-02-17T16:05:50.502Z", "to": "2019-03-11T04:46:55.088Z" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Amplifiers",
   "type": "singlestat",
   "description": "Active Amplifiers from Last successful scanning jobs",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select sum(a.active_amplifiers_count) from core_scantimeseriesresult a left outer join core_scantimeseriesresult b on a.scan_name=b.scan_name and a.created<b.created and a.status=\"SUCCESS\" and b.status=\"SUCCESS\" where b.scan_name is null and a.status=\"SUCCESS\" order by a.created desc;"
    }
   ]
  },
  {
   "title": "Private Amplifiers",
   "type": "singlestat",
   "description": "Amplifiers detected in private address space.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select sum(a.private_amplifiers_count) from core_scantimeseriesresult a left outer join core_scantimeseriesresult b on a.scan_name=b.scan_name and a.created<b.created and a.status=\"SUCCESS\" and b.status=\"SUCCESS\" where b.scan_name is null and a.status=\"SUCCESS\" order by a.created desc;"
    }
   ]
  },
  {
   "title": "Public Amplifiers",
   "type": "singlestat",
   "description": "Amplifiers detected in public address space.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select sum(a.public_amplifiers_count) from core_scantimeseriesresult a left outer join core_scantimeseriesresult b on a.scan_name=b.scan_name and a.created<b.created and a.status=\"SUCCESS\" and b.status=\"SUCCESS\" where b.scan_name is null and a.status=\"SUCCESS\" order by a.created desc;"
    }
   ]
  },
  {
   "title": "Active Amplifiers Time Series",
   "type": "graph",
   "description": "Time series displays the active amplifier counts from the last successful scanning jobs",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "No. of Active Amplifiers" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  scan_name AS metric,\n  active_amplifiers_count\nFROM core_scantimeseriesresult\nWHERE\n  $__timeFilter(created) and status='SUCCESS'\nORDER BY created"
    }
   ]
  },
  {
   "title": "Amplifiers",
   "type": "table",
   "description": "Display amplifier details from last successful scanning jobs",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select a.scan_name, c.address as \"Address\", if(c.private_address, \"Private\", \"Public\") as \"Address Type\", c.amplification_factor as \"Bandwidth Amplification Factor\" from  core_scantimeseriesresult a join core_amplifier c on c.scan_id=a.id left outer join core_scantimeseriesresult b on a.scan_name=b.scan_name and a.created<b.created and a.status=\"SUCCESS\" and b.status=\"SUCCESS\" where b.scan_name is null order by a.created desc;"
    }
   ]
  }
 ]
}