{
 "title": "scan",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Active Amplifiers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select sum(a.active_amplifiers_count) from core_scantimeseriesresult a left outer join core_scantimeseriesresult b on a.scan_name=b.scan_name and a.created<b.created where b.scan_name is null order by a.created desc;"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Active Amplifiers Time Series",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  scan_name AS metric,\n  active_amplifiers_count\nFROM core_scantimeseriesresult\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Amplifiers",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "select a.scan_name,c.address, c.response_size, c.amplification_factor  from  core_scantimeseriesresult a join core_amplifier c on c.scan_id=a.id left outer join core_scantimeseriesresult b on a.scan_name=b.scan_name and a.created<b.created where b.scan_name is null order by a.created desc;\n"
    }
   ]
  }
 ]
}