{
 "title": "Scan Details",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "scan_name",
    "label": "scan name",
    "query": "select name from django_celery_beat_periodictask where name!=\"celery.backend_cleanup\";"
   }
  ]
 },
 "panels": [
  {
   "title": "Run Count",
   "type": "singlestat",
   "description": "Total number of Successful and Failed scanning jobs",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) \nFROM core_scantimeseriesresult\nWHERE\n  scan_name = '$scan_name';"
    }
   ]
  },
  {
   "title": "Active Amplifiers",
   "type": "singlestat",
   "description": "Number of active amplifiers from the last successful scanning job execution!",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select a.active_amplifiers_count from core_scantimeseriesresult a where a.scan_name=\"$scan_name\" and a.status=\"SUCCESS\" order by a.created desc LIMIT 1;"
    }
   ]
  },
  {
   "title": "Last run at",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select DATE_FORMAT(max(created), \"%D %b %Y %r\") from core_scantimeseriesresult where scan_name='$scan_name';"
    }
   ]
  },
  {
   "title": "Last Run Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select status from core_scantimeseriesresult where scan_name='$scan_name' order by created desc limit 1;"
    }
   ]
  },
  {
   "title": "Last Successful run at",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select DATE_FORMAT(max(created), \"%D %b %Y %r\") from core_scantimeseriesresult where scan_name='$scan_name' and status=\"SUCCESS\";"
    }
   ]
  },
  {
   "title": "Scan Arguments",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select json_extract(kwargs, \"$.target_port\") as \"Port\", TRIM(BOTH '\"' FROM json_extract(kwargs, \"$.cron_str\")) as \"Crontab\", TRIM( LEADING '[\"' FROM TRIM(TRAILING '\"]' FROM json_extract(kwargs, \"$.address_range\"))) as \"Target Addresses\" , TRIM(BOTH '\"' FROM json_extract(kwargs, \"$.request_hexdump\")) as \"Request hexdump\" from django_celery_beat_periodictask where name='$scan_name';"
    }
   ]
  },
  {
   "title": "Amplifiers from Last Successful scanning",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "select c.address as \"Address\", c.total_response_size as \"Response Size\", c.amplification_factor as \"Bandwidth Amplification Factor\" from  core_scantimeseriesresult a join core_amplifier c on c.scan_id=a.id left outer join core_scantimeseriesresult b on a.scan_name=b.scan_name and a.created<b.created and a.status=\"SUCCESS\" and b.status=\"SUCCESS\" where b.scan_name is null and a.scan_name=\"$scan_name\" order by a.created desc;"
    }
   ]
  }
 ]
}